# Generated by Django 2.1.7 on 2019-03-14 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=3)),
                ('zip_code', models.PositiveIntegerField(max_length=6)),
                ('delivery_time_min', models.PositiveIntegerField(max_length=4)),
                ('delivery_time_max', models.PositiveIntegerField(max_length=4)),
                ('num_people', models.PositiveSmallIntegerField(verbose_name='size of group')),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual', models.PositiveSmallIntegerField(max_length=4)),
                ('strength_of_pref', models.CharField(max_length=10)),
                ('food_preference', models.CharField(max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_with_friends.Group')),
            ],
        ),
    ]
