# Generated by Django 2.1.7 on 2019-03-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_with_friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='delivery_time_max',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='delivery_time_min',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='zip_code',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='individual',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
