# Generated by Django 2.1.7 on 2019-03-15 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_with_friends', '0002_auto_20190314_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='street_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='zip_code',
            new_name='group_id',
        ),
        migrations.RemoveField(
            model_name='group',
            name='city',
        ),
        migrations.RemoveField(
            model_name='group',
            name='state',
        ),
    ]
