# Generated by Django 2.1.5 on 2019-03-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_with_friends', '0003_auto_20190315_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name_count',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='p_tables',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preferences',
            name='name',
            field=models.CharField(default='person', max_length=100),
            preserve_default=False,
        ),
    ]
