# Generated by Django 2.1.5 on 2019-03-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_with_friends', '0005_auto_20190315_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='group',
            field=models.PositiveIntegerField(),
        ),
    ]
