# Generated by Django 2.1.7 on 2019-03-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_with_friends', '0006_auto_20190315_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.PositiveIntegerField()),
            ],
        ),
    ]
