# Generated by Django 2.1.7 on 2019-03-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_with_friends', '0007_groupnumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupNumber',
        ),
        migrations.AlterField(
            model_name='group',
            name='group_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
