# Generated by Django 2.1.7 on 2019-03-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_with_friends', '0008_auto_20190316_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='dict_prefs',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
