# Generated by Django 2.1.7 on 2019-03-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_with_friends', '0013_auto_20190316_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='strength_of_pref',
            field=models.FloatField(choices=[(2, 'strong'), (1, 'normal'), (0.5, 'weak')]),
        ),
    ]
